server:
  port: 7002

spring:
  activemq:
    in-memory: false
    user: admin
    password: admin
    broker-url: tcp://192.168.1.172:61616
    pool:
      enabled: false
    packages:
      trust-all: true
